// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7P7xrfewhFPbS8VhsuXYb1u1h85y0AeA',
    appId: '1:681191884407:web:ca42129cd37e0394c76872',
    messagingSenderId: '681191884407',
    projectId: 'bizsync-c6a24',
    authDomain: 'bizsync-c6a24.firebaseapp.com',
    storageBucket: 'bizsync-c6a24.appspot.com',
    measurementId: 'G-L3DV4W9XNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDivpnvouFJsoN3MBdoOtDd9TRR9daLXo0',
    appId: '1:681191884407:android:f3bbe36836ce1cecc76872',
    messagingSenderId: '681191884407',
    projectId: 'bizsync-c6a24',
    storageBucket: 'bizsync-c6a24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRsoJjBzRWuFXr18I8rN5A8YPAtzx3Heo',
    appId: '1:681191884407:ios:2e8897ad6182fe26c76872',
    messagingSenderId: '681191884407',
    projectId: 'bizsync-c6a24',
    storageBucket: 'bizsync-c6a24.appspot.com',
    androidClientId: '681191884407-8ul142lc8d0h1vcq8iiar8g8ecdqfu8s.apps.googleusercontent.com',
    iosClientId: '681191884407-ejsnsqf1lpt7svfut14kcf97vfnephio.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRsoJjBzRWuFXr18I8rN5A8YPAtzx3Heo',
    appId: '1:681191884407:ios:5bbf3ffb0c69012bc76872',
    messagingSenderId: '681191884407',
    projectId: 'bizsync-c6a24',
    storageBucket: 'bizsync-c6a24.appspot.com',
    androidClientId: '681191884407-8ul142lc8d0h1vcq8iiar8g8ecdqfu8s.apps.googleusercontent.com',
    iosClientId: '681191884407-vsbb3b6o7l16876jvu4psc6q6pncq0jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizsync.RunnerTests',
  );
}
